#!/usr/bin/env bash
# redirect to another page
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
fill="location /redirect_me {\nrewrite ^/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n}\n"
sudo sed -i "/# Only/ i $fill" /etc/nginx/sites-avalible/default
sudo service nginx restart
