#!/usr/bin/env bash
# redirect to another page
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i '/server_name _;/ a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
