#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
served_by="add_header X-Served-By $(cat /etc/hostname);"
sudo sed -i "/index.html;/ a $served_by" /etc/nginx/sites-enabled/default
sudo service nginx restart
