#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server.
sudo apt-get -y update
sudo apt-get install -y haproxy
sudo sed -i "ss/ENABLED=0/ENABLED=1/g" /etc/default/haproxy
sudo sed -i "\$ a\listen 1602-lb-01\n\tbind *:80\n\tmode http\n\tstats enable\n\tbalance roundrobin\n\tserver 1602-web-01 34.75.116.54:80 check\n\tserver 1602-web-02 35.243.144.246:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy start
