#!/usr/bin/env bash
# displays Holberton School 10 times
count=0
while [ $count -lt 10 ]
do
    echo "Holberton School"
    let count+=1
    if [ $count -eq 9 ]
    then
        echo "Hi"
    fi
done
