#!/usr/bin/env bash
sudo ufw status
sudo ufw default deny incoming
sudo ufw default aloow outgoing
sudo ufw allow OpenSSH
sudo ufw allow in "Nginx HTTP"
sudo ufw allow in "Nginx HTTPS"
sudo ufw enable
